benchmarks:
  mmlu_pro:
    class: MMLUProDataset
    group: llm
    split: test
    has_image: false

  agieval:
    class: AGIEvalDataset
    group: llm
    split: test
    has_image: false

  mmmu_pro:
    class: MMMUProDataset
    group: lmm
    split: test
    has_image: true

  mmbench:
    class: MMBenchDataset
    group: lmm
    split: test
    has_image: true
